### ISSUE TITLE
Please ensure license headers, code of conduct and contributor guidelines are in place

### ISSUE THREAD

**Issue by filmaj** [adobe/generator-tsx#2]
TL;DR copy files over from github.com/adobe/starter-repo

Before adding any code to this repo, please ensure you have in place:

- an Adobe Legal-approved code of conduct
- a `CONTRIBUTING.md` that at a minimum references the need for external contributors to sign Adobe's CLA
- license headers in all source files compatible with your chosen license.

These are requirements from Adobe's legal department. If you'd like help with this, please fill out the form at opensource.corp.adobe.com.

Thanks!
-Fil, Adobe Open Source Office

**Comment by jedmao** [comment]
All set, thanks!
