### ISSUE TITLE
Support polyfill

### ISSUE THREAD

**Issue by silencej** [adobe/generator-tsx#48]
I really like this generator. But now I am having the problem to add polyfill support (e.g. support old Chrome and IE11 etc).

I want to use core-js. relay-compiler demands core-js2, while using core-js2, I come across this:

```
[craco] =============
[craco] Failed to compile.
[craco] 
[craco] ./src/index.tsx
[craco] Module not found: Can't resolve 'core-js/modules/es.array-buffer.constructor' in 'd:\me\svn\FE\src'
```

I know es.array-buffer is core-js3 feature, but I have no clue to find out which package wants it.

In summary, will the support of polyfill be added to the roadmap, or could you give me some hint on how to track this error?

**Comment by jedmao** [comment]
What steps did you take before getting this error? Did you read [this document](https://github.com/facebook/create-react-app/tree/master/packages/react-app-polyfill#react-app-polyfill)?

**Comment by silencej** [comment]
Thanks for the link, a good hint for me.
I was trying to add polyfill with @babel/polyfill

**Comment by jedmao** [comment]
Are you good now then?

**Comment by silencej** [comment]
@jedmao Yes, it's working. Thanks!
